connection: &connection
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: workshops
  password: password

development:
  <<: *connection
  database: redbox_development

test:
  <<: *connection
  database: redbox_test

production:
  <<: *connection
  database: redbox_production